version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: "${PSQL_ADMIN}"
      POSTGRES_PASSWORD: "${PSQL_PASSWORD}"
      POSTGRES_DB: store_default
    ports:
      - "5432:5432"
    volumes:
      - db_store_default:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_store_default: